logo: # add logo name
title: Maccha Maccha
description: > # this means to ignore newlines until "baseurl:"
  Official page of Maccha Sorbet: SecondLife Builder, scripter
  and all round nice bunny.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://macchasorbet.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: Maccha_400x400.jpg # your photo
author-name: Maccha Sorbet # your name
about-author: SecondLife Builder & Scripter. # about author
email: macchasorbet@gmail.com # your email
formspreecode: xwkwnwzl
phone:  # your pnone number
website: https://macchasorbet.github.io/

# Social link
google_url:    # add url link
twitter_url:   https://twitter.com/macchasorbet
instagram_url: # add url link
pinterest_url: # add url link
dribbble_url:  # add url link
facebook_url:  # add url link

# Disqus
discus_identifier: # add your discus identifier.  Not your username.  To get this, register your forum here with a unique ID: https://disqus.com/admin/create/

# Newsletter
mailchimp: # add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Tracker
analytics: G-ZH638R283T

# Paginate
paginate: 12
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins_dir:
  - jekyll-paginate
  - jekyll-sitemap

gems:
  - jekyll-paginate
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
